import { createHmac, timingSafeEqual } from 'crypto';
import type {
  IDataObject,
  INodeExecutionData,
  INodeType,
  INodeTypeDescription,
  IWebhookFunctions,
  IWebhookResponseData,
} from 'n8n-workflow';

const eventOptions = [
  { name: 'All Events', value: '*' },
  { name: 'Account Updates', value: 'account_update.*' },
  { name: 'Coexistence App State', value: 'smb_app_state_sync.*' },
  { name: 'Coexistence Message Echoes', value: 'smb_message_echo.*' },
  { name: 'Flow Submissions', value: 'flow.submission.*' },
  { name: 'History Sync', value: 'history.*' },
  { name: 'Instagram Messages', value: 'instagram.message.*' },
  { name: 'Media Events', value: 'media.*' },
  { name: 'Messages', value: 'message.*' },
  { name: 'Messages: Images', value: 'message.image' },
  { name: 'Messages: Text', value: 'message.text' },
  { name: 'Messenger Messages', value: 'messenger.message.*' },
  { name: 'Status: Failed', value: 'status.failed' },
  { name: 'Status Updates', value: 'status.*' },
  { name: 'Template Updates', value: 'template.*' },
];

export class EasyhookTrigger implements INodeType {
  description: INodeTypeDescription = {
    displayName: 'Easyhook Trigger',
    name: 'easyhookTrigger',
    icon: 'file:easyhook.png',
    group: ['trigger'],
    version: 1,
    description: 'Starts a workflow when Easyhook sends a webhook event',
    eventTriggerDescription: 'Waiting for Easyhook webhook events',
    defaults: {
      name: 'Easyhook Trigger',
    },
    inputs: [],
    outputs: ['main'],
    webhooks: [
      {
        name: 'default',
        httpMethod: 'POST',
        responseMode: 'onReceived',
        responseData: 'firstEntryJson',
        path: 'easyhook',
      },
    ],
    properties: [
      {
        displayName: 'Easyhook Webhook URL',
        name: 'webhookUrl',
        type: 'notice',
        default: 'Copy the Production URL from this trigger and paste it in Easyhook as the destination URL for an easyhook subscription.',
      },
      {
        displayName: 'Expected Events',
        name: 'events',
        type: 'multiOptions',
        options: eventOptions,
        default: ['*'],
        description: 'Documentation-only filter for this workflow. Configure the real provider, scope, and event filter in the Easyhook portal subscription.',
      },
      {
        displayName: 'Security',
        name: 'authType',
        type: 'options',
        options: [
          { name: 'Bearer Secret (Recommended)', value: 'bearer' },
          { name: 'Custom Header Secret', value: 'customHeader' },
          { name: 'HMAC Signature', value: 'hmac' },
          { name: 'No Auth', value: 'none' },
        ],
        default: 'bearer',
        description: 'Must match the auth type configured for this hook in the Easyhook portal.',
      },
      {
        displayName: 'Bearer Secret',
        name: 'bearerSecret',
        type: 'string',
        typeOptions: { password: true },
        default: '',
        required: true,
        description: 'Paste the secret generated by Easyhook. Easyhook sends it as Authorization: Bearer <secret>.',
        displayOptions: {
          show: {
            authType: ['bearer'],
          },
        },
      },
      {
        displayName: 'Header Name',
        name: 'customHeaderName',
        type: 'string',
        default: 'X-Webhook-Token',
        required: true,
        displayOptions: {
          show: {
            authType: ['customHeader'],
          },
        },
      },
      {
        displayName: 'Header Secret',
        name: 'customHeaderSecret',
        type: 'string',
        typeOptions: { password: true },
        default: '',
        required: true,
        description: 'Paste the custom header secret generated by Easyhook.',
        displayOptions: {
          show: {
            authType: ['customHeader'],
          },
        },
      },
      {
        displayName: 'HMAC Secret',
        name: 'hmacSecret',
        type: 'string',
        typeOptions: { password: true },
        default: '',
        required: true,
        description: 'Paste the Easyhook HMAC secret. Easyhook signs the raw body as X-Easyhook-Signature: sha256=<hex>.',
        displayOptions: {
          show: {
            authType: ['hmac'],
          },
        },
      },
      {
        displayName: 'Include Headers',
        name: 'includeHeaders',
        type: 'boolean',
        default: false,
      },
      {
        displayName: 'Include Query',
        name: 'includeQuery',
        type: 'boolean',
        default: false,
      },
    ],
  };

  async webhook(this: IWebhookFunctions): Promise<IWebhookResponseData> {
    if (!validateEasyhookAuth.call(this)) {
      const response = this.getResponseObject();
      response.status(401).json({ ok: false, error: 'invalid_easyhook_webhook_secret' });
      return { noWebhookResponse: true };
    }

    const body = this.getBodyData();
    const includeHeaders = this.getNodeParameter('includeHeaders', false) as boolean;
    const includeQuery = this.getNodeParameter('includeQuery', false) as boolean;

    const json: IDataObject = {
      ...body,
    };
    if (includeHeaders) json.headers = this.getHeaderData() as IDataObject;
    if (includeQuery) json.query = this.getQueryData() as IDataObject;

    const workflowData: INodeExecutionData[][] = [[{ json }]];
    return {
      workflowData,
      webhookResponse: { ok: true },
    };
  }
}

function validateEasyhookAuth(this: IWebhookFunctions): boolean {
  const authType = this.getNodeParameter('authType', 'bearer') as string;
  if (authType === 'none') return true;

  const headers = this.getHeaderData();
  if (authType === 'bearer') {
    const secret = this.getNodeParameter('bearerSecret', '') as string;
    const authorization = readHeader(headers, 'authorization');
    if (!secret || !authorization) return false;
    const token = authorization.replace(/^Bearer\s+/i, '').trim();
    return safeCompare(token, secret);
  }

  if (authType === 'customHeader') {
    const headerName = this.getNodeParameter('customHeaderName', 'X-Webhook-Token') as string;
    const secret = this.getNodeParameter('customHeaderSecret', '') as string;
    const headerValue = readHeader(headers, headerName);
    if (!secret || !headerValue) return false;
    return safeCompare(headerValue, secret);
  }

  if (authType === 'hmac') {
    const secret = this.getNodeParameter('hmacSecret', '') as string;
    const signature = readHeader(headers, 'x-easyhook-signature');
    if (!secret || !signature?.startsWith('sha256=')) return false;
    const provided = signature.slice('sha256='.length);
    const rawBody = readRawBody(this.getRequestObject(), this.getBodyData());
    const expected = createHmac('sha256', secret).update(rawBody).digest('hex');
    return safeCompare(provided, expected);
  }

  return false;
}

function readHeader(headers: Record<string, string | string[] | undefined>, name: string): string | null {
  const needle = name.toLowerCase();
  const entry = Object.entries(headers).find(([key]) => key.toLowerCase() === needle);
  const value = entry?.[1];
  if (Array.isArray(value)) return value[0] ?? null;
  return typeof value === 'string' ? value : null;
}

function readRawBody(request: { rawBody?: unknown }, fallbackBody: IDataObject): Buffer | string {
  const rawBody = request.rawBody;
  if (Buffer.isBuffer(rawBody)) return rawBody;
  if (typeof rawBody === 'string') return rawBody;
  if (rawBody !== undefined) return JSON.stringify(rawBody);
  return JSON.stringify(fallbackBody);
}

function safeCompare(a: string, b: string): boolean {
  const aBuffer = Buffer.from(a);
  const bBuffer = Buffer.from(b);
  if (aBuffer.length !== bBuffer.length) return false;
  return timingSafeEqual(aBuffer, bBuffer);
}
